development:
  adapter: postgresql
  encoding: unicode
  database: railstagram_dev
  pool: 5
  username: cesar
  password: cesar420

test:
  adapter: postgresql
  encoding: unicode
  database: railstagram_test
  pool: 5
  username: cesar
  password: cesar420