development:
  adapter: postgresql
  encoding: unicode
  database: railstagram_dev
  pool: 5
  username: eduardo
  password: eagzv.999

test:
  adapter: postgresql
  encoding: unicode
  database: railstagram_test
  pool: 5
  username: eduardo
  password: eagzv.999